services:
  app:
    container_name: front-pacto-pela-economia
    image: front-pacto-pela-economia:1.0
    ports:
      - "5174:80"
    depends_on:
      - api
    restart: unless-stopped 
  api:
    container_name: api-pacto-pela-economia
    image: api-pacto-pela-economia:1.0
    restart: unless-stopped